// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfRMFlkTc3j79eSbM2JhVseSTZDQ1DuPY',
    appId: '1:634661164827:web:e589434da2065f8d80a5be',
    messagingSenderId: '634661164827',
    projectId: 'visual-learning-b1abf',
    authDomain: 'visual-learning-b1abf.firebaseapp.com',
    storageBucket: 'visual-learning-b1abf.firebasestorage.app',
    measurementId: 'G-G474B1BCVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVRH-GmHe5UAGoeDKlXIOLg7CbGxZJ2ig',
    appId: '1:634661164827:android:bd9f5290361c249280a5be',
    messagingSenderId: '634661164827',
    projectId: 'visual-learning-b1abf',
    storageBucket: 'visual-learning-b1abf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB238BvNe8s6WQaxGZJYifSmLRoSionQrI',
    appId: '1:634661164827:ios:98907e9d8d0b917280a5be',
    messagingSenderId: '634661164827',
    projectId: 'visual-learning-b1abf',
    storageBucket: 'visual-learning-b1abf.firebasestorage.app',
    iosBundleId: 'com.example.visualLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB238BvNe8s6WQaxGZJYifSmLRoSionQrI',
    appId: '1:634661164827:ios:98907e9d8d0b917280a5be',
    messagingSenderId: '634661164827',
    projectId: 'visual-learning-b1abf',
    storageBucket: 'visual-learning-b1abf.firebasestorage.app',
    iosBundleId: 'com.example.visualLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfRMFlkTc3j79eSbM2JhVseSTZDQ1DuPY',
    appId: '1:634661164827:web:6daa949c5e1628af80a5be',
    messagingSenderId: '634661164827',
    projectId: 'visual-learning-b1abf',
    authDomain: 'visual-learning-b1abf.firebaseapp.com',
    storageBucket: 'visual-learning-b1abf.firebasestorage.app',
    measurementId: 'G-JME3G4V562',
  );
}
